/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ClassroomSetEditorBody model module.
 * @module model/ClassroomSetEditorBody
 * @version 1.0.0-oas3
 */
export default class ClassroomSetEditorBody {
  /**
   * Constructs a new <code>ClassroomSetEditorBody</code>.
   * @alias module:model/ClassroomSetEditorBody
   * @class
   * @param studentID {Number} 
   */
  constructor(studentID) {
    this.studentID = studentID;
  }

  /**
   * Constructs a <code>ClassroomSetEditorBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClassroomSetEditorBody} obj Optional instance to populate.
   * @return {module:model/ClassroomSetEditorBody} The populated <code>ClassroomSetEditorBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClassroomSetEditorBody();
      if (data.hasOwnProperty('studentID'))
        obj.studentID = ApiClient.convertToType(data['studentID'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} studentID
 */
ClassroomSetEditorBody.prototype.studentID = undefined;

