/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Classroom model module.
 * @module model/Classroom
 * @version 1.0.0-oas3
 */
export default class Classroom {
  /**
   * Constructs a new <code>Classroom</code>.
   * @alias module:model/Classroom
   * @class
   * @param id {Number} 
   * @param editingStudentID {Number} 
   * @param users {Array.<Number>} 
   */
  constructor(id, editingStudentID, users) {
    this.id = id;
    this.editingStudentID = editingStudentID;
    this.users = users;
  }

  /**
   * Constructs a <code>Classroom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Classroom} obj Optional instance to populate.
   * @return {module:model/Classroom} The populated <code>Classroom</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Classroom();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('editingStudentID'))
        obj.editingStudentID = ApiClient.convertToType(data['editingStudentID'], 'Number');
      if (data.hasOwnProperty('users'))
        obj.users = ApiClient.convertToType(data['users'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Classroom.prototype.id = undefined;

/**
 * @member {Number} editingStudentID
 */
Classroom.prototype.editingStudentID = undefined;

/**
 * @member {Array.<Number>} users
 */
Classroom.prototype.users = undefined;

