/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Student from './Student';

/**
 * The GroupOut model module.
 * @module model/GroupOut
 * @version 1.0.0-oas3
 */
export default class GroupOut {
  /**
   * Constructs a new <code>GroupOut</code>.
   * @alias module:model/GroupOut
   * @class
   * @param groupID {Number} 
   * @param name {String} 
   * @param maxMembers {Number} 
   * @param members {Array.<module:model/Student>} 
   */
  constructor(groupID, name, maxMembers, members) {
    this.groupID = groupID;
    this.name = name;
    this.maxMembers = maxMembers;
    this.members = members;
  }

  /**
   * Constructs a <code>GroupOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupOut} obj Optional instance to populate.
   * @return {module:model/GroupOut} The populated <code>GroupOut</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupOut();
      if (data.hasOwnProperty('groupID'))
        obj.groupID = ApiClient.convertToType(data['groupID'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('maxMembers'))
        obj.maxMembers = ApiClient.convertToType(data['maxMembers'], 'Number');
      if (data.hasOwnProperty('members'))
        obj.members = ApiClient.convertToType(data['members'], [Student]);
    }
    return obj;
  }
}

/**
 * @member {Number} groupID
 */
GroupOut.prototype.groupID = undefined;

/**
 * @member {String} name
 */
GroupOut.prototype.name = undefined;

/**
 * @member {Number} maxMembers
 */
GroupOut.prototype.maxMembers = undefined;

/**
 * @member {Array.<module:model/Student>} members
 */
GroupOut.prototype.members = undefined;

