/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GroupsUnenrollBody model module.
 * @module model/GroupsUnenrollBody
 * @version 1.0.0-oas3
 */
export default class GroupsUnenrollBody {
  /**
   * Constructs a new <code>GroupsUnenrollBody</code>.
   * @alias module:model/GroupsUnenrollBody
   * @class
   * @param studentID {Number} 
   * @param groupID {Number} 
   */
  constructor(studentID, groupID) {
    this.studentID = studentID;
    this.groupID = groupID;
  }

  /**
   * Constructs a <code>GroupsUnenrollBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupsUnenrollBody} obj Optional instance to populate.
   * @return {module:model/GroupsUnenrollBody} The populated <code>GroupsUnenrollBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupsUnenrollBody();
      if (data.hasOwnProperty('studentID'))
        obj.studentID = ApiClient.convertToType(data['studentID'], 'Number');
      if (data.hasOwnProperty('groupID'))
        obj.groupID = ApiClient.convertToType(data['groupID'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} studentID
 */
GroupsUnenrollBody.prototype.studentID = undefined;

/**
 * @member {Number} groupID
 */
GroupsUnenrollBody.prototype.groupID = undefined;

