/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Coach from '../model/Coach';

/**
* Coach service.
* @module api/CoachApi
* @version 1.0.0-oas3
*/
export default class CoachApi {

    /**
    * Constructs a new CoachApi. 
    * @alias module:api/CoachApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getCoach operation.
     * @callback moduleapi/CoachApi~getCoachCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Coach{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get coach by ID
     * @param {Number} coachID Coach ID to get
     * @param {module:api/CoachApi~getCoachCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCoach(coachID, callback) {
      
      let postBody = null;
      // verify the required parameter 'coachID' is set
      if (coachID === undefined || coachID === null) {
        throw new Error("Missing the required parameter 'coachID' when calling getCoach");
      }

      let pathParams = {
        'coachID': coachID
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Coach;

      return this.apiClient.callApi(
        '/coach/{coachID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the postCoach operation.
     * @callback moduleapi/CoachApi~postCoachCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Coach{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new coach given their name
     * @param {module:model/Coach} body JSON object with the studentID and groupID
     * @param {module:api/CoachApi~postCoachCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    postCoach(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling postCoach");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Coach;

      return this.apiClient.callApi(
        '/coach', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}