/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YouChessApi);
  }
}(this, function(expect, YouChessApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YouChessApi.ClassroomApi();
  });

  describe('(package)', function() {
    describe('ClassroomApi', function() {
      describe('getClassroom', function() {
        it('should call getClassroom successfully', function(done) {
          // TODO: uncomment, update parameter values for getClassroom call and complete the assertions
          /*

          instance.getClassroom(groupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YouChessApi.Classroom);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('groupGroupIDClassroomSetEditorPost', function() {
        it('should call groupGroupIDClassroomSetEditorPost successfully', function(done) {
          // TODO: uncomment, update parameter values for groupGroupIDClassroomSetEditorPost call
          /*

          instance.groupGroupIDClassroomSetEditorPost(body, groupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateClassroom', function() {
        it('should call updateClassroom successfully', function(done) {
          // TODO: uncomment, update parameter values for updateClassroom call and complete the assertions
          /*

          instance.updateClassroom(body, groupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YouChessApi.Classroom);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
