/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YouChessApi);
  }
}(this, function(expect, YouChessApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Classroom', function() {
      beforeEach(function() {
        instance = new YouChessApi.Classroom();
      });

      it('should create an instance of Classroom', function() {
        // TODO: update the code to test Classroom
        expect(instance).to.be.a(YouChessApi.Classroom);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property editingStudentID (base name: "editingStudentID")', function() {
        // TODO: update the code to test the property editingStudentID
        expect(instance).to.have.property('editingStudentID');
        // expect(instance.editingStudentID).to.be(expectedValueLiteral);
      });

      it('should have the property users (base name: "users")', function() {
        // TODO: update the code to test the property users
        expect(instance).to.have.property('users');
        // expect(instance.users).to.be(expectedValueLiteral);
      });

    });
  });

}));
