/*
 * YouChess API
 * This is YouChess API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: nievange@ece.auth.gr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Classroom from './model/Classroom';
import ClassroomSetEditorBody from './model/ClassroomSetEditorBody';
import Coach from './model/Coach';
import GroupIn from './model/GroupIn';
import GroupOut from './model/GroupOut';
import GroupsEnrollBody from './model/GroupsEnrollBody';
import GroupsUnenrollBody from './model/GroupsUnenrollBody';
import Student from './model/Student';
import ClassroomApi from './api/ClassroomApi';
import CoachApi from './api/CoachApi';
import GroupApi from './api/GroupApi';
import StudentApi from './api/StudentApi';

/**
* This_is_YouChess_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var YouChessApi = require('index'); // See note below*.
* var xxxSvc = new YouChessApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new YouChessApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new YouChessApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new YouChessApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0-oas3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Classroom model constructor.
     * @property {module:model/Classroom}
     */
    Classroom,

    /**
     * The ClassroomSetEditorBody model constructor.
     * @property {module:model/ClassroomSetEditorBody}
     */
    ClassroomSetEditorBody,

    /**
     * The Coach model constructor.
     * @property {module:model/Coach}
     */
    Coach,

    /**
     * The GroupIn model constructor.
     * @property {module:model/GroupIn}
     */
    GroupIn,

    /**
     * The GroupOut model constructor.
     * @property {module:model/GroupOut}
     */
    GroupOut,

    /**
     * The GroupsEnrollBody model constructor.
     * @property {module:model/GroupsEnrollBody}
     */
    GroupsEnrollBody,

    /**
     * The GroupsUnenrollBody model constructor.
     * @property {module:model/GroupsUnenrollBody}
     */
    GroupsUnenrollBody,

    /**
     * The Student model constructor.
     * @property {module:model/Student}
     */
    Student,

    /**
    * The ClassroomApi service constructor.
    * @property {module:api/ClassroomApi}
    */
    ClassroomApi,

    /**
    * The CoachApi service constructor.
    * @property {module:api/CoachApi}
    */
    CoachApi,

    /**
    * The GroupApi service constructor.
    * @property {module:api/GroupApi}
    */
    GroupApi,

    /**
    * The StudentApi service constructor.
    * @property {module:api/StudentApi}
    */
    StudentApi
};
